name: Cargo Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER: x86_64-linux-gnu-gcc
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-gnu-gcc
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal
          rustup default ${{ matrix.toolchain }}
          rustup target add ${{ matrix.target }} --toolchain ${{ matrix.toolchain }}
      - run: sudo apt-get install -y gcc-aarch64-linux-gnu gcc-x86-64-linux-gnu
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-0
          key: ${{ matrix.target }}
      - run: cargo clippy --verbose --target ${{ matrix.target }}
      - run: cargo build --verbose --target ${{ matrix.target }}
      - run: cargo test --verbose --target ${{ matrix.target }}
        if: (startsWith(matrix.target, 'x86_64-') && runner.arch == 'X64') || (startsWith(matrix.target, 'aarch64-') && runner.arch == 'ARM64')
